import type { ConnectedAccount, ConnectorSignal } from './types'

export const mockConnectedAccounts: ConnectedAccount[] = [
  {
    id: 'acct-google-workspace',
    label: 'Work Google Workspace',
    accountAddress: 'operator@atlas.example',
    provider: 'Gmail / Google Workspace',
    providerType: 'email-calendar',
    connectionMethod: 'oauth-later',
    healthStatus: 'healthy',
    lastSignalScanAt: '2026-05-18T08:30:00.000Z',
    signalTypes: ['meeting', 'urgent-follow-up', 'schedule-pressure', 'client-opportunity'],
    readOnly: true,
  },
  {
    id: 'acct-outlook-client',
    label: 'Client Outlook Calendar',
    accountAddress: 'client.ops@outlook.com',
    provider: 'Microsoft 365 / Outlook Calendar',
    providerType: 'calendar',
    connectionMethod: 'oauth-later',
    healthStatus: 'needs-review',
    lastSignalScanAt: '2026-05-17T16:00:00.000Z',
    signalTypes: ['meeting', 'travel', 'personal-work-clash'],
    readOnly: true,
  },
  {
    id: 'acct-icloud-personal',
    label: 'Personal iCloud Calendar',
    accountAddress: 'personal@icloud.com',
    provider: 'iCloud / CalDAV',
    providerType: 'calendar',
    connectionMethod: 'caldav',
    healthStatus: 'setup-required',
    lastSignalScanAt: '2026-05-15T12:00:00.000Z',
    signalTypes: ['personal-work-clash', 'schedule-pressure'],
    readOnly: true,
  },
]

export const mockConnectorSignals: ConnectorSignal[] = [
  {
    id: 'signal-meeting-pack',
    accountId: 'acct-google-workspace',
    type: 'meeting',
    title: 'Client review meeting tomorrow',
    summary: 'A client review appears on the calendar with preparation time needed today.',
    confidence: 0.88,
    suggestedQueueAction: 'Prepare meeting pack',
    occurredAt: '2026-05-18T08:30:00.000Z',
  },
  {
    id: 'signal-travel-mention',
    accountId: 'acct-outlook-client',
    type: 'travel',
    title: 'Possible travel planning mention',
    summary: 'Calendar context suggests travel planning may affect scheduling later this week.',
    confidence: 0.72,
    suggestedQueueAction: 'Review travel brief',
    occurredAt: '2026-05-18T09:00:00.000Z',
  },
  {
    id: 'signal-urgent-follow-up',
    accountId: 'acct-google-workspace',
    type: 'urgent-follow-up',
    title: 'Urgent follow-up signal',
    summary: 'An approved account produced a follow-up signal connected to a warm client opportunity.',
    confidence: 0.84,
    suggestedQueueAction: 'Follow up client',
    occurredAt: '2026-05-18T09:15:00.000Z',
  },
  {
    id: 'signal-schedule-pressure',
    accountId: 'acct-google-workspace',
    type: 'schedule-pressure',
    title: 'Schedule pressure building',
    summary: 'Meetings and focus blocks appear compressed, with one potential scheduling clash.',
    confidence: 0.8,
    suggestedQueueAction: 'Check scheduling clash',
    occurredAt: '2026-05-18T10:00:00.000Z',
  },
  {
    id: 'signal-finance-pressure',
    accountId: 'acct-google-workspace',
    type: 'finance-pressure',
    title: 'Finance review mention',
    summary: 'A finance-related thread suggests a payment timing review may be useful.',
    confidence: 0.68,
    suggestedQueueAction: 'Review urgent email signal',
    occurredAt: '2026-05-18T10:20:00.000Z',
  },
]
